name: First interaction

on:
  issues:
    types: [ opened ]

jobs:
  interaction:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hello! Thank you for posting an issue.
          
          As a reminder, have you checked the [wiki](https://github.com/jannekem/actions-playground/wiki)
          for common issues?
        pr-message: |
          Thank you for your first pull request!
